# Intersection between test sets

Another team also worked on Identification. Here we found the matches between both sets.

In [9]:
import pandas as pd
import re
import os

In [6]:
raw_train='/content/gdrive/MyDrive/MIDS/W210/Animal_Identification/datasets/leopard/train/images'

In [2]:
test2=pd.read_csv('/content/safari_sleuth_leopard_test.csv')
test2

     Unnamed: 0     leopard_paths  stripped  in_test
0             7  000000004606.jpg  4606.jpg     True
1            14  000000004550.jpg  4550.jpg     True
2            18  000000002976.jpg  2976.jpg     True
3            30  000000005077.jpg  5077.jpg     True
4            36  000000006287.jpg  6287.jpg     True
..          ...               ...       ...      ...
668        6677  000000002218.jpg  2218.jpg     True
669        6682  000000001330.jpg  1330.jpg     True
670        6695  000000000456.jpg   456.jpg     True
671        6703  000000002482.jpg  2482.jpg     True
672        6729  000000000355.jpg   355.jpg     True

[673 rows x 4 columns]

In [3]:
test2=test2.rename(columns={'Unnamed: 0':'id'})
test2

       id     leopard_paths  stripped  in_test
0       7  000000004606.jpg  4606.jpg     True
1      14  000000004550.jpg  4550.jpg     True
2      18  000000002976.jpg  2976.jpg     True
3      30  000000005077.jpg  5077.jpg     True
4      36  000000006287.jpg  6287.jpg     True
..    ...               ...       ...      ...
668  6677  000000002218.jpg  2218.jpg     True
669  6682  000000001330.jpg  1330.jpg     True
670  6695  000000000456.jpg   456.jpg     True
671  6703  000000002482.jpg  2482.jpg     True
672  6729  000000000355.jpg   355.jpg     True

[673 rows x 4 columns]

In [4]:
test2['img_name']=test2.apply(lambda x: 'leop_%s_%s' % (x['id'],x['leopard_paths']), axis=1)
test2.head()

   id     leopard_paths  stripped  in_test                  img_name
0   7  000000004606.jpg  4606.jpg     True   leop_7_000000004606.jpg
1  14  000000004550.jpg  4550.jpg     True  leop_14_000000004550.jpg
2  18  000000002976.jpg  2976.jpg     True  leop_18_000000002976.jpg
3  30  000000005077.jpg  5077.jpg     True  leop_30_000000005077.jpg
4  36  000000006287.jpg  6287.jpg     True  leop_36_000000006287.jpg

In [7]:
test2['path']= test2.apply(lambda x: '%s/%s' % (raw_train,x['img_name']), axis=1)
test2.head()

,id,leopard_paths,stripped,in_test,img_name,path
0,7,000000004606.jpg,4606.jpg,True,leop_7_000000004606.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...
1,14,000000004550.jpg,4550.jpg,True,leop_14_000000004550.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...
2,18,000000002976.jpg,2976.jpg,True,leop_18_000000002976.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...
3,30,000000005077.jpg,5077.jpg,True,leop_30_000000005077.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...
4,36,000000006287.jpg,6287.jpg,True,leop_36_000000006287.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...

In [11]:
## Our dataset - test
raw_test='/content/drive/MyDrive/MIDS/W210/Animal_Identification/datasets/leopard/test/images'
# raw_dev='/content/gdrive/MyDrive/MIDS/W210/Animal_Identification/datasets/leopard/dev/images'
img_test= os.listdir(raw_test)
# img_dev= os.listdir(raw_dev)

In [12]:
len(img_test)

688

In [13]:
tmp=[]
for name in img_test:
  text=re.search('[0-9]+.jpg',name).group(0)
  text=text.lstrip("0")
  tmp.append(text)
tmp[:10]

['8.jpg',
 '12.jpg',
 '13.jpg',
 '34.jpg',
 '35.jpg',
 '36.jpg',
 '44.jpg',
 '56.jpg',
 '63.jpg',
 '70.jpg']

In [14]:
test2['both_testsets']=test2.apply(lambda x: True if x['stripped'] in tmp else False, axis=1)
test2.head()

,id,leopard_paths,stripped,in_test,img_name,path,both_testsets
0,7,000000004606.jpg,4606.jpg,True,leop_7_000000004606.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True
1,14,000000004550.jpg,4550.jpg,True,leop_14_000000004550.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,False
2,18,000000002976.jpg,2976.jpg,True,leop_18_000000002976.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,False
3,30,000000005077.jpg,5077.jpg,True,leop_30_000000005077.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,False
4,36,000000006287.jpg,6287.jpg,True,leop_36_000000006287.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,False

In [15]:
matches=test2[test2.both_testsets==True]
matches.head()

,id,leopard_paths,stripped,in_test,img_name,path,both_testsets
0,7,000000004606.jpg,4606.jpg,True,leop_7_000000004606.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True
21,118,000000005241.jpg,5241.jpg,True,leop_118_000000005241.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True
34,292,000000005194.jpg,5194.jpg,True,leop_292_000000005194.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True
50,538,000000005366.jpg,5366.jpg,True,leop_538_000000005366.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True
60,625,000000004916.jpg,4916.jpg,True,leop_625_000000004916.jpg,/content/gdrive/MyDrive/MIDS/W210/Animal_Ident...,True

In [16]:
matches_files=[]
for img in matches['stripped']:
  print(img)
  text=re.search('[0-9]+.jpg',img).group(0)
  text=text.lstrip("0")
  print('#### CHECK TEST #####')

  for name in img_test:
    # print(name)
    text2=re.search('[0-9]+.jpg',name).group(0)
    # print(text2)
    text2=text2.lstrip("0")
    # print(text, text2)

    if text2==text:
      print(f"Same files founded: {text2} and {text}")
      matches_files.append(name)
      break
matches_files

4606.jpg
#### CHECK TEST #####
Same files founded: 4606.jpg and 4606.jpg
5241.jpg
#### CHECK TEST #####
Same files founded: 5241.jpg and 5241.jpg
5194.jpg
#### CHECK TEST #####
Same files founded: 5194.jpg and 5194.jpg
5366.jpg
#### CHECK TEST #####
Same files founded: 5366.jpg and 5366.jpg
4916.jpg
#### CHECK TEST #####
Same files founded: 4916.jpg and 4916.jpg
4678.jpg
#### CHECK TEST #####
Same files founded: 4678.jpg and 4678.jpg
2882.jpg
#### CHECK TEST #####
Same files founded: 2882.jpg and 2882.jpg
4787.jpg
#### CHECK TEST #####
Same files founded: 4787.jpg and 4787.jpg
536.jpg
#### CHECK TEST #####
Same files founded: 536.jpg and 536.jpg
3706.jpg
#### CHECK TEST #####
Same files founded: 3706.jpg and 3706.jpg
5874.jpg
#### CHECK TEST #####
Same files founded: 5874.jpg and 5874.jpg
4290.jpg
#### CHECK TEST #####
Same files founded: 4290.jpg and 4290.jpg
6627.jpg
#### CHECK TEST #####
Same files founded: 6627.jpg and 6627.jpg
3584.jpg
#### CHECK TEST #####
Same files founded: 3584.jpg and 3584.jpg
2352.jpg
#### CHECK TEST #####
Same files founded: 2352.jpg and 2352.jpg
4315.jpg
#### CHECK TEST #####
Same files founded: 4315.jpg and 4315.jpg
3610.jpg
#### CHECK TEST #####
Same files founded: 3610.jpg and 3610.jpg
3777.jpg
#### CHECK TEST #####
Same files founded: 3777.jpg and 3777.jpg
844.jpg
#### CHECK TEST #####
Same files founded: 844.jpg and 844.jpg
265.jpg
#### CHECK TEST #####
Same files founded: 265.jpg and 265.jpg
6766.jpg
#### CHECK TEST #####
Same files founded: 6766.jpg and 6766.jpg
5565.jpg
#### CHECK TEST #####
Same files founded: 5565.jpg and 5565.jpg
5813.jpg
#### CHECK TEST #####
Same files founded: 5813.jpg and 5813.jpg
5950.jpg
#### CHECK TEST #####
Same files founded: 5950.jpg and 5950.jpg
1611.jpg
#### CHECK TEST #####
Same files founded: 1611.jpg and 1611.jpg
6723.jpg
#### CHECK TEST #####
Same files founded: 6723.jpg and 6723.jpg
5423.jpg
#### CHECK TEST #####
Same files founded: 5423.jpg and 5423.jpg
6476.jpg
#### CHECK TEST #####
Same files founded: 6476.jpg and 6476.jpg
5061.jpg
#### CHECK TEST #####
Same files founded: 5061.jpg and 5061.jpg
6560.jpg
#### CHECK TEST #####
Same files founded: 6560.jpg and 6560.jpg
248.jpg
#### CHECK TEST #####
Same files founded: 248.jpg and 248.jpg
848.jpg
#### CHECK TEST #####
Same files founded: 848.jpg and 848.jpg
5252.jpg
#### CHECK TEST #####
Same files founded: 5252.jpg and 5252.jpg
227.jpg
#### CHECK TEST #####
Same files founded: 227.jpg and 227.jpg
1522.jpg
#### CHECK TEST #####
Same files founded: 1522.jpg and 1522.jpg
2255.jpg
#### CHECK TEST #####
Same files founded: 2255.jpg and 2255.jpg
3341.jpg
#### CHECK TEST #####
Same files founded: 3341.jpg and 3341.jpg
2889.jpg
#### CHECK TEST #####
Same files founded: 2889.jpg and 2889.jpg
555.jpg
#### CHECK TEST #####
Same files founded: 555.jpg and 555.jpg
2582.jpg
#### CHECK TEST #####
Same files founded: 2582.jpg and 2582.jpg
3295.jpg
#### CHECK TEST #####
Same files founded: 3295.jpg and 3295.jpg
315.jpg
#### CHECK TEST #####
Same files founded: 315.jpg and 315.jpg
508.jpg
#### CHECK TEST #####
Same files founded: 508.jpg and 508.jpg
5663.jpg
#### CHECK TEST #####
Same files founded: 5663.jpg and 5663.jpg
6241.jpg
#### CHECK TEST #####
Same files founded: 6241.jpg and 6241.jpg
869.jpg
#### CHECK TEST #####
Same files founded: 869.jpg and 869.jpg
4870.jpg
#### CHECK TEST #####
Same files founded: 4870.jpg and 4870.jpg
3455.jpg
#### CHECK TEST #####
Same files founded: 3455.jpg and 3455.jpg
3751.jpg
#### CHECK TEST #####
Same files founded: 3751.jpg and 3751.jpg
1186.jpg
#### CHECK TEST #####
Same files founded: 1186.jpg and 1186.jpg
4880.jpg
#### CHECK TEST #####
Same files founded: 4880.jpg and 4880.jpg
3445.jpg
#### CHECK TEST #####
Same files founded: 3445.jpg and 3445.jpg
5262.jpg
#### CHECK TEST #####
Same files founded: 5262.jpg and 5262.jpg
2735.jpg
#### CHECK TEST #####
Same files founded: 2735.jpg and 2735.jpg
2843.jpg
#### CHECK TEST #####
Same files founded: 2843.jpg and 2843.jpg
552.jpg
#### CHECK TEST #####
Same files founded: 552.jpg and 552.jpg
409.jpg
#### CHECK TEST #####
Same files founded: 409.jpg and 409.jpg
5804.jpg
#### CHECK TEST #####
Same files founded: 5804.jpg and 5804.jpg
6519.jpg
#### CHECK TEST #####
Same files founded: 6519.jpg and 6519.jpg
454.jpg
#### CHECK TEST #####
Same files founded: 454.jpg and 454.jpg
4330.jpg
#### CHECK TEST #####
Same files founded: 4330.jpg and 4330.jpg
2383.jpg
#### CHECK TEST #####
Same files founded: 2383.jpg and 2383.jpg
2939.jpg
#### CHECK TEST #####
Same files founded: 2939.jpg and 2939.jpg
972.jpg
#### CHECK TEST #####
Same files founded: 972.jpg and 972.jpg
2482.jpg
#### CHECK TEST #####
Same files founded: 2482.jpg and 2482.jpg

['leop_271_004606.jpg',
 'leop_273_005241.jpg',
 'leop_272_005194.jpg',
 'leop_272_005366.jpg',
 'leop_280_004916.jpg',
 'leop_284_004678.jpg',
 'leop_212_002882.jpg',
 'leop_287_004787.jpg',
 'leop_12_000536.jpg',
 'leop_265_003706.jpg',
 'leop_282_005874.jpg',
 'leop_272_004290.jpg',
 'leop_265_006627.jpg',
 'leop_259_003584.jpg',
 'leop_121_002352.jpg',
 'leop_291_004315.jpg',
 'leop_260_003610.jpg',
 'leop_250_003777.jpg',
 'leop_15_000844.jpg',
 'leop_9_000265.jpg',
 'leop_430_006766.jpg',
 'leop_302_005565.jpg',
 'leop_280_005813.jpg',
 'leop_316_005950.jpg',
 'leop_25_001611.jpg',
 'leop_252_006723.jpg',
 'leop_272_005423.jpg',
 'leop_415_006476.jpg',
 'leop_284_005061.jpg',
 'leop_423_006560.jpg',
 'leop_8_000248.jpg',
 'leop_15_000848.jpg',
 'leop_289_005252.jpg',
 'leop_7_000227.jpg',
 'leop_25_001522.jpg',
 'leop_91_002255.jpg',
 'leop_248_003341.jpg',
 'leop_212_002889.jpg',
 'leop_12_000555.jpg',
 'leop_182_002582.jpg',
 'leop_133_003295.jpg',
 'leop_12_000315.jpg',
 'leop_14_000508.jpg',
 'leop_248_005663.jpg',
 'leop_330_006241.jpg',
 'leop_15_000869.jpg',
 'leop_278_004870.jpg',
 'leop_253_003455.jpg',
 'leop_265_003751.jpg',
 'leop_0_001186.jpg',
 'leop_277_004880.jpg',
 'leop_252_003445.jpg',
 'leop_289_005262.jpg',
 'leop_205_002735.jpg',
 'leop_217_002843.jpg',
 'leop_12_000552.jpg',
 'leop_12_000409.jpg',
 'leop_280_005804.jpg',
 'leop_288_006519.jpg',
 'leop_13_000454.jpg',
 'leop_281_004330.jpg',
 'leop_80_002383.jpg',
 'leop_229_002939.jpg',
 'leop_15_000972.jpg',
 'leop_153_002482.jpg']

In [17]:
%cd /content/
df_matches=pd.DataFrame(matches_files, columns=['img_name'])
df_matches.to_csv('test_comparison_set.csv')

/content

In [ ]:
source='/content/gdrive/MyDrive/MIDS/W210/Animal_Identification/datasets/leopard/test/images'
destination='/content/gdrive/MyDrive/MIDS/W210/Animal_Identification/datasets/test65'

for fileName in matches_files:
  new_source=f'{source}/{fileName}'
  new_destination=f'{destination}/{fileName}'
  !cp $new_source $new_destination

In [18]:
test2=test2.drop(["path","img_name"], axis=1)
test2

       id     leopard_paths  stripped  in_test  both_testsets
0       7  000000004606.jpg  4606.jpg     True           True
1      14  000000004550.jpg  4550.jpg     True          False
2      18  000000002976.jpg  2976.jpg     True          False
3      30  000000005077.jpg  5077.jpg     True          False
4      36  000000006287.jpg  6287.jpg     True          False
..    ...               ...       ...      ...            ...
668  6677  000000002218.jpg  2218.jpg     True          False
669  6682  000000001330.jpg  1330.jpg     True          False
670  6695  000000000456.jpg   456.jpg     True          False
671  6703  000000002482.jpg  2482.jpg     True           True
672  6729  000000000355.jpg   355.jpg     True          False

[673 rows x 5 columns]

In [19]:
test2.to_csv('matches_test_sets.csv')